### ISSUE TITLE
Crear presentación: Accesibilidad y Registro

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#1]
Crear el contenido para mostrar funcionalidad accesibilidad y registro.

**Comment by angelmotta** [comment]
Hacer presentación:
Mostrar funcionalidad de accesibilidad y registro a la app

**Comment by Piero16301** [comment]
- Link Presentación inicial:
[https://drive.google.com/open?id=1yhY8hjY3NtRxSy-rbyaqrvX2U-IQfZZZKJq9GrrjAZ0](url)
- Link logo:
[https://drive.google.com/open?id=11YA7Uo5k9BOyluA-Xrl7bcEQLpWOyaAZ](url)
- Link video las funcionalidades:
[https://vimeo.com/406656345](url)
- Pitch individual (registro, accesibilidad y usuarios):
[https://drive.google.com/open?id=1BWRXW4LHxTgqgAzFOrxM003qwoFT5PX2arcwvz-P4S0](url)
