### ISSUE TITLE
Hacer la presentación de roles de usuario

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#10]
Desarrollar la presentación para mostrar de manera gráfica los 3 roles de usuario que contempla la aplicación.

**Comment by Piero16301** [comment]
- Pitch individual (registro, accesibilidad y usuarios):
[https://drive.google.com/open?id=1BWRXW4LHxTgqgAzFOrxM003qwoFT5PX2arcwvz-P4S0](url)
