### ISSUE TITLE
Crear presentación: funcionalidad offline

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#5]
Crear presentación que muestre funcionalidad offline:
- Poder descargar los videos.
- Poder descargar el audio y  ppts (para contenidos propios)

**Comment by davidalejandrolazopampa** [comment]
Adjunto el link del ppt: (Finalizado)
https://docs.google.com/presentation/d/1K506WS6YVS_MaXFfzuCAT8Tu2nXTGdDox3rGziHFKYU/edit?usp=sharing
