### ISSUE TITLE
Idear nombre para la app

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#6]
Idear nombre candidato para la app
Cada uno debe crear un nombre para la app. Se elegirá el mejor nombre.

- [x] @CarlosCupe 
- [x] @Piero16301 
- [x] @angelmotta 
- [x] @davidalejandrolazopampa 
- [x] @JeanleeRoy

**Comment by CarlosCupe** [comment]
Study

**Comment by Piero16301** [comment]
Sugerencia de nombre: Brainy

**Comment by JeanleeRoy** [comment]
Sugerencia de nombre: Apprendo

**Comment by angelmotta** [comment]
Como les comenté en la reunión mi sugerencia de nombre es: EstudiApp

**Comment by kaitoc** [comment]
Sugerencia: **Stadi** (Study peruanizado)

**Comment by davidalejandrolazopampa** [comment]
Sugiero [APE: Aporta Perú Edu]

**Comment by angelmotta** [comment]
Nombre acordado:
**Apprendo**
