### ISSUE TITLE
Definir el problema

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#7]
Tu apoyo para definir el problema.
El problema es el motivo por el cual surge este proyecto.

**Comment by JeanleeRoy** [comment]
Problema identificado y definido.
Contenido correspondiente a la tarea asignada
[https://drive.google.com/file/d/1-qqRcqFgaz5dZUnGv5Pu-Qn-WwEGlou7/view?usp=sharing](url)

**Comment by JeanleeRoy** [comment]
Issue cerrado
