### ISSUE TITLE
Definir que otras alternativas existen

### ISSUE THREAD

**Issue by angelmotta** [cs2901-2020-1/pitch-side_project#9]
Define de manera clara y coherente dos opciones alternativas a la solución propuesta así como también muestra las diferencias comparativas entre ellas.

**Comment by kaitoc** [comment]
Avance: https://docs.google.com/presentation/d/1106UKvdvTymD3azU53KC9-EL9Q71T9AdXuAYwyx7ejU/edit?usp=sharing
